export const userActions = {
  GET_LIST_USER: "GET_LIST_USER",
  GET_LIST_USER_SUCCESS: "GET_LIST_USER_SUCCESS",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
};

export const categoryActions = {
  ADD_CATEGORY: "ADD_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  GET_LIST_CATEGORY: "GET_LIST_CATEGORY",
  GET_LIST_CATEGORY_SUCCESS: "GET_LIST_CATEGORY_SUCCESS",
};

export const productActions = {
  ADD_PRODUCT: "ADD_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  GET_LIST_PRODUCT: "GET_LIST_PRODUCT",
  GET_LIST_PRODUCT_SUCCESS: "GET_LIST_PRODUCT_SUCCESS",
  ADD_PRODUCT_DETAIL: "ADD_PRODUCT_DETAIL",
  UPDATE_PRODUCT_DETAIL: "UPDATE_PRODUCT_DETAIL",
  UPLOAD_PRODUCT_IMAGE: "UPLOAD_PRODUCT_IMAGE",
  DELETE_PRODUCT_IMAGE: "DELETE_PRODUCT_IMAGE"
}
